# Generated by Django 3.2.4 on 2021-06-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='photo',
            field=models.ImageField(default='', editable=False, upload_to='books'),
        ),
    ]
