# Generated by Django 3.2.4 on 2021-06-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='photo',
        ),
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(default='', editable=False, upload_to='images'),
        ),
    ]
