# Generated by Django 3.2.4 on 2021-06-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20210609_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(default='einstein_book.jpg', editable=False, upload_to='images'),
        ),
    ]
